### ISSUE TITLE
Addnode

### ISSUE THREAD

**Issue by le2Ks** [kchirayath/turkeycoin#1]
Hi, any addnode? Thx

**Comment by le2Ks** [comment]
I love the logo xD

**Comment by linkedlist94** [comment]
Haha thanks, updated src should have seed node

**Comment by le2Ks** [comment]
Got it! Thanks!

**Comment by le2Ks** [comment]
Hey do you have a discord group for the project, and for scamcoin too?

**Comment by linkedlist94** [comment]
https://discord.gg/6QuFBPQs - Gobblecoin
https://discord.gg/6QuFBPQs - Scamcoin 
:D

**Comment by le2Ks** [comment]
Awesome! joining!
